services:
  - type: web
    name: dardja-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: dardja-frontend
    env: node
    rootDir: frontend
    buildCommand: npm run build
    startCommand: npm run preview
    plan: free
